version: '3'

services:
  postgres:
    image: postgres:9.3
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      POSTGRES_DB: otoy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: runwols123
    ports:
    - 5432:5432

  kafka:
    image: wurstmeister/kafka:0.10.2.1
    depends_on:
      - zookeeper
    ports:
    - 9092:9092
    environment:
      KAFKA_CREATE_TOPICS: "message:3:1"
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_MESSAGE_MAX_BYTES: 200000000

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
    - 2181:2181

  consul:
    image: consul
    ports:
    - 8500:8500

  workers:
    build: .
    command: >
      bash -c "./quizes --act=consumer"
    restart: on-failure
    depends_on:
      - postgres
      - zookeeper
      - kafka
      - consul
    links:
      - postgres
      - zookeeper
      - kafka
      - consul

  migrate:
    build: .
    command: >
      bash -c "./quizes --act=migrate"
    restart: on-failure
    depends_on:
    - postgres
    - zookeeper
    - kafka
    - consul
    links:
    - postgres
    - zookeeper
    - kafka
    - consul

  quizes:
    build: .
    restart: on-failure
    depends_on:
      - postgres
      - zookeeper
      - kafka
      - consul
      - workers
    links:
      - postgres
      - zookeeper
      - kafka
      - consul
    ports:
      - 8080:8080